config/routes.rb
Rails.application.routes.draw do
  get 'inicio/index'

  root 'inicio#index'
  # Rutas de recurso Ejemplo
  resources :ejemplos 
  
  # Rutas para Tipos
  resources :tipos

  # Rutas para Elementos y Comentarios
  resources :elementos do
    resources :comentarios
  end
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
	belongs_to :elemento
end

app/models/ejemplo.rb
class Ejemplo < ActiveRecord::Base
end

app/models/elemento.rb
class Elemento < ActiveRecord::Base
  belongs_to :tipo
	has_many :comentarios
  mount_uploader :imagen, ImagenUploader
end

app/models/tipo.rb
class Tipo < ActiveRecord::Base
	has_many :elementos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  class ComentariosController < ApplicationController
  def index
    @comentarios = Comentario.all
  end

  def show
  end

  def new
    @comentario = Comentario.new
  end

  def edit
  end

  def create
    @comentario = Comentario.new(comentario_params)

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to @comentario, notice: 'Comentario creado exitosamente' }
        format.json { render :show, status: :created, location: @comentario }
      else
        format.html { render :new }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario, notice: 'Comentario actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to comentarios_url, notice: 'Comentario borrado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    def comentario_params
      params.require(:comentario).permit(:nombre)
    end
end

end

app/controllers/ejemplos_controller.rb
class EjemplosController < ApplicationController
  before_action :set_ejemplo, only: [:show, :edit, :update, :destroy]

  # GET /ejemplos
  # GET /ejemplos.json
  def index
    @ejemplos = Ejemplo.all
  end

  # GET /ejemplos/1
  # GET /ejemplos/1.json
  def show
  end

  # GET /ejemplos/new
  def new
    @ejemplo = Ejemplo.new
  end

  # GET /ejemplos/1/edit
  def edit
  end

  # POST /ejemplos
  # POST /ejemplos.json
  def create
    @ejemplo = Ejemplo.new(ejemplo_params)

    respond_to do |format|
      if @ejemplo.save
        format.html { redirect_to @ejemplo, notice: 'Ejemplo was successfully created.' }
        format.json { render :show, status: :created, location: @ejemplo }
      else
        format.html { render :new }
        format.json { render json: @ejemplo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ejemplos/1
  # PATCH/PUT /ejemplos/1.json
  def update
    respond_to do |format|
      if @ejemplo.update(ejemplo_params)
        format.html { redirect_to @ejemplo, notice: 'Ejemplo was successfully updated.' }
        format.json { render :show, status: :ok, location: @ejemplo }
      else
        format.html { render :edit }
        format.json { render json: @ejemplo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ejemplos/1
  # DELETE /ejemplos/1.json
  def destroy
    @ejemplo.destroy
    respond_to do |format|
      format.html { redirect_to ejemplos_url, notice: 'Ejemplo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ejemplo
      @ejemplo = Ejemplo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ejemplo_params
      params.require(:ejemplo).permit(:nombre, :numero)
    end
end

app/controllers/elementos_controller.rb
class ElementosController < ApplicationController
  before_action :set_elemento, only: [:show, :edit, :update, :destroy]

  def index
    @elementos = Elemento.all
  end

  def show
    @comentarios = Comentario.where(elemento_id: @elemento) 
  end

  def new
    @elemento = Elemento.new
  end

  def edit
  end

  def create
    @elemento = Elemento.new(elemento_params)

    respond_to do |format|
      if @elemento.save
        format.html { redirect_to @elemento, notice: 'Elemento creado exitosamente' }
        format.json { render :show, status: :created, location: @elemento }
      else
        format.html { render :new }
        format.json { render json: @elemento.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @elemento.update(elemento_params)
        format.html { redirect_to @elemento, notice: 'Elemento actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @elemento }
      else
        format.html { render :edit }
        format.json { render json: @elemento.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @elemento.destroy
    respond_to do |format|
      format.html { redirect_to elementos_url, notice: 'Elemento borrado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    def set_elemento
      @elemento = Elemento.find(params[:id])
    end

    def elemento_params
      params.require(:elemento).permit(:nombre, :descripcion, :imagen, :foto, :precio, :caracteristicas, :tipo_id, :created_at, :updated_at)
    end
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def index
    if params[:tipo] 
      @elementos = Elemento.where(tipo_id: params[:tipo]) 
    else
      @elementos = Elemento.all
    end
    @tipos = Tipo.all
  end
end

app/controllers/tipos_controller.rb
class TiposController < ApplicationController
  before_action :set_tipo, only: [:show, :edit, :update, :destroy]

  def index
    @tipos = Tipo.all
  end

  def show
  end

  def new
    @tipo = Tipo.new
  end

  def edit
  end

  def create
    @tipo = Tipo.new(tipo_params)

    respond_to do |format|
      if @tipo.save
        format.html { redirect_to @tipo, notice: 'Tipo creado exitosamente' }
        format.json { render :show, status: :created, location: @tipo }
      else
        format.html { render :new }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @tipo.update(tipo_params)
        format.html { redirect_to @tipo, notice: 'Tipo actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @tipo }
      else
        format.html { render :edit }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tipo.destroy
    respond_to do |format|
      format.html { redirect_to tipos_url, notice: 'Tipo borrado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    def set_tipo
      @tipo = Tipo.find(params[:id])
    end

    def tipo_params
      params.require(:tipo).permit(:nombre)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/ejemplos_helper.rb
module EjemplosHelper
end

app/helpers/elementos_helper.rb
module ElementosHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/views/comentarios/_form.html.erb
<%= form_for(@ejemplo) do |f| %>
  <% if @ejemplo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ejemplo.errors.count, "error") %> prohibited this ejemplo from being saved:</h2>

      <ul>
      <% @ejemplo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :numero %><br>
    <%= f.number_field :numero %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comentarios/edit.html.erb
<h1>Editing ejemplo</h1>

<%= render 'form' %>

<%= link_to 'Show', @ejemplo %> |
<%= link_to 'Back', ejemplos_path %>

app/views/comentarios/index.html.erb
<h1>Listing ejemplos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Numero</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ejemplos.each do |ejemplo| %>
      <tr>
        <td><%= ejemplo.nombre %></td>
        <td><%= ejemplo.numero %></td>
        <td><%= link_to 'Show', ejemplo %></td>
        <td><%= link_to 'Edit', edit_ejemplo_path(ejemplo) %></td>
        <td><%= link_to 'Destroy', ejemplo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ejemplo', new_ejemplo_path %>

app/views/comentarios/new.html.erb
<h1>New ejemplo</h1>

<%= render 'form' %>

<%= link_to 'Back', ejemplos_path %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @ejemplo.nombre %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @ejemplo.numero %>
</p>

<%= link_to 'Edit', edit_ejemplo_path(@ejemplo) %> |
<%= link_to 'Back', ejemplos_path %>

app/views/ejemplos/_form.html.erb
<%= form_for(@ejemplo) do |f| %>
  <% if @ejemplo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ejemplo.errors.count, "error") %> prohibited this ejemplo from being saved:</h2>

      <ul>
      <% @ejemplo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :numero %><br>
    <%= f.number_field :numero %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ejemplos/edit.html.erb
<h1>Editing ejemplo</h1>

<%= render 'form' %>

<%= link_to 'Show', @ejemplo %> |
<%= link_to 'Back', ejemplos_path %>

app/views/ejemplos/index.html.erb
<h1>Listing ejemplos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Numero</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ejemplos.each do |ejemplo| %>
      <tr>
        <td><%= ejemplo.nombre %></td>
        <td><%= ejemplo.numero %></td>
        <td><%= link_to 'Show', ejemplo %></td>
        <td><%= link_to 'Edit', edit_ejemplo_path(ejemplo) %></td>
        <td><%= link_to 'Destroy', ejemplo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ejemplo', new_ejemplo_path %>

app/views/ejemplos/new.html.erb
<h1>New ejemplo</h1>

<%= render 'form' %>

<%= link_to 'Back', ejemplos_path %>

app/views/ejemplos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @ejemplo.nombre %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @ejemplo.numero %>
</p>

<%= link_to 'Edit', edit_ejemplo_path(@ejemplo) %> |
<%= link_to 'Back', ejemplos_path %>

app/views/elementos/_form.html.erb
<%= form_for(@elemento) do |f| %>
  <% if @elemento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@elemento.errors.count, "error") %> prohibited this elemento from being saved:</h2>

      <ul>
      <% @elemento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :imagen %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :precio %><br>
    <%= f.number_field :precio %>
  </div>
  <div class="field">
    <%= f.label :caracteristicas %><br>
    <%= f.text_field :caracteristicas %>
  </div>
  <div class="field">
    <%= f.label :foto %><br>
    <%= f.file_field :foto %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.collection_select :tipo_id, Tipo.all, :id, :nombre, :selected => @elemento.tipo_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <p> Modificado por última vez: <%= @elemento.updated_at %> </p>
<% end %>

app/views/elementos/_listado.html.erb
<% @elementos.each do |elemento| %>
  <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
      <%= image_tag elemento.imagen_url.to_s %>
      <div class="caption">
        <h3> <%= elemento.nombre %> </h3>
        <p><%= elemento.descripcion %></p>
        <p>
          <%= link_to 'Ver', elemento_path(elemento), class: "btn btn-primary" %>
        </p>
      </div>
    </div>
  </div>
<% end %>

app/views/elementos/edit.html.erb
<h1>Editing elemento</h1>

<%= render 'form' %>

<%= link_to 'Show', @elemento %> |
<%= link_to 'Back', elementos_path %>

app/views/elementos/index.html.erb
<h1>Listing elementos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Numero</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @elementos.each do |elemento| %>
      <tr>
        <td><%= elemento.nombre %></td>
        <td><%= elemento.descripcion %></td>
        <td><%= link_to 'Show', elemento %></td>
        <td><%= link_to 'Edit', edit_elemento_path(elemento) %></td>
        <td><%= link_to 'Destroy', elemento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New elemento', new_elemento_path %>

app/views/elementos/new.html.erb
<h1>New elemento</h1>

<%= render 'form' %>

<%= link_to 'Back', elementos_path %>

app/views/elementos/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @elemento.imagen_url.to_s %>
<p>
  <strong>Nombre:</strong>
  <%= @elemento.nombre %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @elemento.descripcion %>
</p>
<p>
  <strong>Precio:</strong>
  <%= @elemento.precio %>
</p>
<p>
  <strong>Caracteristicas:</strong>
  <%= @elemento.caracteristicas %>
</p>
<p>
  <strong>Tipo:</strong>
  <%= @elemento.tipo.nombre %>
</p>

app/views/inicio/index.html.erb
<div class="row">
  <div class="col-md-2">
    <%= render 'tipos/listado' %>
  </div>
  <div class="col-md-10">
    <%= render 'elementos/listado' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProyectoRailsCTN</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Proyecto</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/tipos/_form.html.erb
<%= form_for(@tipo) do |f| %>
  <% if @tipo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tipo.errors.count, "error") %> prohibited this tipo from being saved:</h2>

      <ul>
      <% @tipo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tipos/_listado.html.erb
<ul class="nav nav-pills nav-stacked">
  <% @tipos.each do |tipo| %>
    <li><%= link_to tipo.nombre, tipo %></li>
  <% end %>
</ul>

app/views/tipos/edit.html.erb
<h1>Editing tipo</h1>

<%= render 'form' %>

<%= link_to 'Show', @tipo %> |
<%= link_to 'Back', tipos_path %>

app/views/tipos/index.html.erb
<h1>Listing tipos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Numero</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipos.each do |tipo| %>
      <tr>
        <td><%= tipo.nombre %></td>
        <td><%= link_to 'Show', tipo %></td>
        <td><%= link_to 'Edit', edit_tipo_path(tipo) %></td>
        <td><%= link_to 'Destroy', tipo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New tipo', new_tipo_path %>

app/views/tipos/new.html.erb
<h1>New ejemplo</h1>

<%= render 'form' %>

<%= link_to 'Back', ejemplos_path %>

app/views/tipos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @tipo.nombre %>
</p>


<%= link_to 'Edit', edit_tipo_path(@tipo) %> |
<%= link_to 'Back', tipos_path %>